### ISSUE TITLE
Deleting destination from itinerary error

### ISSUE THREAD

**Issue by 70A5** [vantezzen/wonderrail#2]
_To start off, I would like to thank you for building this great tool for planning interrail journeys, the user experience is fantastic._

### Now, the error I'm encountering.

Application error: a client-side exception has occurred (see the browser console for more information).

The browser console shows the following:

9a3362b0-149f-49e9-907b-845b9ee5ae4b:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
9a3362b0-149f-49e9-907b-845b9ee5ae4b:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
794-942eb35d6182a07d.js:1 Object
794-942eb35d6182a07d.js:1 Object
794-942eb35d6182a07d.js:1 Object
488-c3c73db72949e576.js:1 TypeError: Cannot read properties of undefined (reading 'timerange')
    at nb (794-942eb35d6182a07d.js:1:148616)
    at rs (bce60fc1-d49f395f4486e3d9.js:9:38883)
    at lg (bce60fc1-d49f395f4486e3d9.js:9:54283)
    at iv (bce60fc1-d49f395f4486e3d9.js:9:112695)
    at oR (bce60fc1-d49f395f4486e3d9.js:9:90087)
    at bce60fc1-d49f395f4486e3d9.js:9:89936
    at oD (bce60fc1-d49f395f4486e3d9.js:9:89943)
    at ow (bce60fc1-d49f395f4486e3d9.js:9:87645)
    at nJ (bce60fc1-d49f395f4486e3d9.js:9:36784)
    at n1 (bce60fc1-d49f395f4486e3d9.js:9:37400)
window.console.error @ 488-c3c73db72949e576.js:1
/api/hostels/search?location=Hlavn%C3%AD+m%C4%9Bsto+Praha%2C+%C4%8Cesko&startDate=2023-10-14&duration=2:1     Failed to load resource: the server responded with a status of 404 ()

**Comment by vantezzen** [comment]
Thank you for reporting this. I've now deployed the new design which includes a fix for deleting cities
